Hero
Melaverde1987/eat-your-chocolate-frog pull request #12
Opened 2023-06-05 16:08 UTC by Olexander-rozmax

2023-06-05 17:32 UTC, Melaverde1987 requested changes

2023-06-05 17:32 UTC, Melaverde1987 commented on src/css/hero.css
> +display: none;
тут display робить текст невидимим для краулерів, написала в html як краще

2023-06-05 17:32 UTC, Melaverde1987 commented on src/partials/hero.html
> +<h1 class="hero-tite">Hero</h1>
це всередину секції, додати клас visually-hidden

2023-06-05 17:32 UTC, Melaverde1987 commented on src/partials/hero.html
> +    <div class=hero-blocks>
назву класу в лапки

2023-06-05 17:32 UTC, Melaverde1987 commented on src/css/hero.css
> +  width: 335px;
тут max-width

2023-06-05 17:32 UTC, Melaverde1987 commented on src/partials/hero.html
> +  <div class="container">
контейнеру треба задати max-width з макету

2023-06-05 17:32 UTC, Melaverde1987 commented on src/css/hero.css
> +  left: 0px;
left top тут не потрібні

2023-06-05 17:32 UTC, Melaverde1987 commented on src/partials/hero.html
> +          <a href=""></a>
href="#howitsmade"

2023-06-05 17:32 UTC, Melaverde1987 commented on src/css/hero.css
> +fill: #FD9222;
fill треба перенести на клас arrow-button

2023-06-05 17:32 UTC, Melaverde1987 commented on src/css/hero.css
> +transform: rotate(-90deg);
де в макеті є обертання, не можу знайти

2023-06-05 17:32 UTC, Melaverde1987 commented on src/css/hero.css
> +    height: 102px;
висота не потрібна

2023-06-05 17:32 UTC, Melaverde1987 commented on src/css/hero.css
> +  justify-content: flex-start;
justify-content: space between

2023-06-05 19:58 UTC, A-ZuMa commented on src/partials/hero.html
> +      <div class="hero-scrol-btn-container">
Снопку треба зробити як посилання, де в якості посилання вказати якір на "contactus"

2023-06-05 20:02 UTC, A-ZuMa commented on src/css/hero.css
> +color: #FFFFFF;
Гарною практикою, та корисною звичкою стане вікористання дінамічних змінних, як мінімум на колір.
Список всіх змінних є в основному файлі CSS в розділі :root COLORS

2023-06-05 20:11 UTC, A-ZuMa commented on src/partials/hero.html
> +          <a href=""></a>
Доповню. Згідно до вимог ТЗ ндо секції
- Кнопка “Buy now” відкриває модальне вікно “Buy now”. (треба домовитись з розробником секціх про id для переходу, та додати до коду.)
- Кнопка “How it’s made” є якірним посиланням до секції “How it’s made”. (href="#howitsmade")

2023-06-06 07:22 UTC, Olexander-rozmax commented on src/css/hero.css
> +display: none;
зрозумів

2023-06-06 07:26 UTC, Olexander-rozmax commented on src/partials/hero.html
> +<h1 class="hero-tite">Hero</h1>
зробив так:

.hero-tite {
visibility: hidden;
}

2023-06-06 07:28 UTC, Olexander-rozmax commented on src/partials/hero.html
> +    <div class=hero-blocks>
не  зрозумів  що треба виправити

2023-06-06 07:29 UTC, Olexander-rozmax commented on src/css/hero.css
> +  width: 335px;
виправив

2023-06-06 07:37 UTC, Olexander-rozmax commented
почав  вносити корективи  все  поїхало,  тож не  знаю  чи вносити ті  правки

2023-06-06 19:42 UTC, Melaverde1987 approved these changes

2023-06-06 19:42 UTC, merged