Origin/topsellers
Melaverde1987/eat-your-chocolate-frog pull request #14
Opened 2023-06-05 19:13 UTC by Anastasiia211

2023-06-06 18:33 UTC, Melaverde1987 requested changes

2023-06-06 18:33 UTC, Melaverde1987 commented on src/css/top-sellers.css
> +    width: 306px;
max width 306px
 інакше текст вилазить за межі

2023-06-06 18:33 UTC, Melaverde1987 commented on src/css/top-sellers.css
>  .top-sellers {
потрібен тільки верхній паддінг і він інший

2023-06-06 18:33 UTC, Melaverde1987 commented on src/css/top-sellers.css
> +    line-height: 1.16px;
line height без px

2023-06-06 18:33 UTC, Melaverde1987 commented on src/css/top-sellers.css
> +  .top-sellers-title {
на десктопі і таблеті цей елемент не має нижнього мерджіна

2023-06-06 18:33 UTC, Melaverde1987 commented on src/css/top-sellers.css
> +    margin-bottom: 72px;
на десктопі і таблеті цей елемент не має нижнього мерджіна

2023-06-06 18:33 UTC, Melaverde1987 commented on src/css/top-sellers.css
> +@media only screen and (max-width: 1200px) {
@media only screen and (max-width: 1199px)

2023-06-06 18:33 UTC, Melaverde1987 commented on src/partials/top-sellers.html
>  <section class="top-sellers">
додати id="topsellers"

2023-06-06 20:27 UTC, Anastasiia211 commented on src/css/top-sellers.css
> +    width: 306px;
виправила ,дякую

2023-06-06 20:27 UTC, Anastasiia211 commented on src/css/top-sellers.css
>  .top-sellers {
виправила ,дякую

2023-06-06 20:27 UTC, Anastasiia211 commented on src/css/top-sellers.css
> +  .top-sellers-title {
виправила ,дякую

2023-06-06 20:27 UTC, Anastasiia211 commented on src/css/top-sellers.css
> +    margin-bottom: 72px;
виправила ,дякую

2023-06-06 20:27 UTC, Anastasiia211 commented on src/css/top-sellers.css
> +@media only screen and (max-width: 1200px) {
виправила ,дякую

2023-06-06 20:27 UTC, Anastasiia211 commented on src/partials/top-sellers.html
>  <section class="top-sellers">
додала

2023-06-06 21:09 UTC, Anastasiia211 commented on src/css/top-sellers.css
> +    line-height: 1.16px;
змінила

2023-06-07 08:04 UTC, Melaverde1987 approved these changes

2023-06-07 08:05 UTC, merged