Footer
Melaverde1987/eat-your-chocolate-frog pull request #2
Opened 2023-06-02 12:44 UTC by A-ZuMa

Зробив секцію згідно макету.
Врахував особливості маштабування.
Додав ховери, та транзішени.
До посилань зробив якір, надав додаткову інформацію розробникам суміжних секцій.

Прохання перевірити секцію, та прийняти до основної гілки.

Чекаю на зауваження.
Дякую.

2023-06-02 14:44 UTC, Melaverde1987 commented on src/css/footer.css
> +.footer-title {
font-weight: 500;
font-size: 28px;

2023-06-02 14:58 UTC, Melaverde1987 requested changes

2023-06-02 14:58 UTC, Melaverde1987 commented on src/css/footer.css
> +.footer-title {
font-weight: 500;
    font-size: 28px;
max-width: 300px;

тут просто різні розміри тексту на різних девайсах

2023-06-02 14:58 UTC, Melaverde1987 commented on src/css/footer.css
> +    gap: 50px;
gap на макеті трохи інший

2023-06-02 15:38 UTC, A-ZuMa commented on src/css/footer.css
> +    gap: 50px;
Чому? Саме 50px. Скрін закинув у Slack

2023-06-02 15:40 UTC, A-ZuMa commented on src/css/footer.css
> +.footer-title {
Додав медіа.

2023-06-02 17:29 UTC, Melaverde1987 requested changes

2023-06-02 17:29 UTC, Melaverde1987 commented on src/css/footer.css
> +.footer-menu-list {
тут в мобільному gap 18px

2023-06-02 17:29 UTC, Melaverde1987 commented on src/css/footer.css
> +    gap: 63px;
тут треба max-width 293px інакше іконки вилазять поза контейнер на десктопі

2023-06-02 17:39 UTC, A-ZuMa commented on src/css/footer.css
> +    gap: 63px;
Є таке діло. Макет дійсно "дуже цікавий" :)
Додав.

2023-06-02 17:40 UTC, A-ZuMa commented on src/css/footer.css
> +.footer-menu-list {
Fixed

2023-06-03 08:41 UTC, Melaverde1987 requested changes

2023-06-03 08:41 UTC, Melaverde1987 commented on src/css/footer.css
> +.footer-contacts-list {
gap: 4px;

2023-06-03 08:41 UTC, Melaverde1987 commented on src/css/footer.css
> +.footer-socials-icons {
width: 24px;
    display: inline-block;
    height: 24px;
тут треба ширину і висоту, щоб вміст контейнера не вилазив поза <a>

2023-06-03 08:41 UTC, Melaverde1987 commented on src/partials/footer.html
> +                class="footer-contacts-item link"
не зовсім ясно, нащо тут клас link

2023-06-03 08:41 UTC, Melaverde1987 commented on src/css/footer.css
> +.footer-socials-item {
не можу знайти говер, для якого цей перехід

2023-06-03 08:45 UTC, A-ZuMa commented on src/css/footer.css
> +.footer-contacts-list {
Done

2023-06-03 08:59 UTC, A-ZuMa commented on src/css/footer.css
> +.footer-socials-icons {
Не розумію чому? На макеті іконки 22px x 22px я на icon поставив такі самі розміри.

Зараз передивився ще раз. МАКЕТ КРИВИЙ, або навмисно зробленний так, щоб людей плутати.
На мобільному контейнер 22px, іконка 18,5px
На таблетці контейнер 24px, іконка 20px 

Це треба через JS в HTML змінювати width та height для них?

<svg class="icon" width="22" height="22">
                  <use
                    href="./img/sprite.svg#instagram"
                    aria-label="instagram icon"
                  ></use>
                </svg>

2023-06-03 09:36 UTC, A-ZuMa commented on src/partials/footer.html
> +                class="footer-contacts-item link"
То вже звичка, щоб прибрати стандартне оформлення для послань (italic, підкреслення & etc).

2023-06-03 09:40 UTC, A-ZuMa commented on src/css/footer.css
> +.footer-socials-item {
Не зрозумів. Про який говер і перехід йде мова?

2023-06-03 09:46 UTC, A-ZuMa commented on src/css/footer.css
> +.footer-socials-item {
Так, це помилка, правільно .footer-menu-item
Виправив

2023-06-03 09:48 UTC, A-ZuMa commented on src/css/footer.css
> +.footer-socials-icons {
Зараз зробив так

.footer-socials-icons {
  display: inline-block;
  width: 22px;
  height: 22px;
  fill: var(--white);
  transition: fill 300ms cubic-bezier(0.4, 0, 0.2, 1);
}
@media only screen and (min-width: 768px) {
  .footer-socials-icons {
    width: 24px;
    height: 24px;
  }
}

2023-06-03 22:11 UTC, Melaverde1987 approved these changes

2023-06-03 22:11 UTC, merged