Feature advantages
Melaverde1987/eat-your-chocolate-frog pull request #3
Opened 2023-06-02 18:27 UTC by volodimirBriukhovetskyi

Зробив правки. Переглянь будь ласка.

2023-06-03 09:08 UTC, Melaverde1987 requested changes

2023-06-03 09:08 UTC, Melaverde1987 commented on src/css/advantages.css
> +  margin-right: auto;
не зовсім ясно, для чого тут gap i margin right

2023-06-03 09:08 UTC, Melaverde1987 commented on src/css/advantages.css
> +  .advantages-list {
у мобільній версії тут нижній проміжок між елементами більший, там або з паддінгом, або більший геп. з паддінгом мабуть краща ідея з огляду на останній елемент, там теж є ця відстань

2023-06-03 12:46 UTC, volodimirBriukhovetskyi commented
bug fix зроблений.


сб, 3 июн. 2023 г. в 12:08, Melaverde1987 ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/css/advantages.css
> <https://github.com/Melaverde1987/eat-your-chocolate-frog/pull/3#discussion_r1215355258>
> :
>
> > +  font-size: 18px;
> +  line-height: 1.22;
> +
> +  color: var(--white);
> +}
> +.advantages-text {
> +  font-weight: 400;
> +  line-height: 1.21;
> +  letter-spacing: -0.02em;
> +  max-width: 308px;
> +
> +  color: rgba(255, 255, 255, 0.7);
> +}
> +
> +.advantages-link {
> +  margin-right: auto;
>
> не зовсім ясно, для чого тут gap i margin right
> ------------------------------
>
> In src/css/advantages.css
> <https://github.com/Melaverde1987/eat-your-chocolate-frog/pull/3#discussion_r1215355700>
> :
>
> > +  justify-content: center;
> +  align-items: center;
> +  padding: 0px;
> +  gap: 7.3px;
> +
> +  width: 62px;
> +  height: 62px;
> +
> +  border: 1px solid rgba(255, 255, 255, 0.5);
> +  border-radius: 50%;
> +}
> ***@***.*** screen and (min-width: 768px) {
> +  .advantages {
> +    padding: 50px 0px;
> +  }
> +  .advantages-list {
>
> у мобільній версії тут нижній проміжок між елементами більший, там або з
> паддінгом, або більший геп. з паддінгом мабуть краща ідея з огляду на
> останній елемент, там теж є ця відстань
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Melaverde1987/eat-your-chocolate-frog/pull/3#pullrequestreview-1459103474>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6OPUIJ3P7BBK4FOMXCBEVDXJL5ITANCNFSM6AAAAAAYYUYRFI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2023-06-03 22:24 UTC, Melaverde1987 commented on src/css/advantages.css
> +.advantages-link {
зараз все добре, тільки маленьке зауваження - іконки не є <a>, a <div>, це по аналогії з нашою домашньою. крім того, говер-фокус на них - звідки він? на макеті не можу такого знайти

2023-06-04 09:14 UTC, volodimirBriukhovetskyi commented
Вітаю! Зробив спаном ховер фокус прибрав. Останнє питання (шлях в svg
залишати як є, чи крапку на початку видаляти)


вс, 4 июн. 2023 г. в 01:24, Melaverde1987 ***@***.***>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/css/advantages.css
> <https://github.com/Melaverde1987/eat-your-chocolate-frog/pull/3#discussion_r1215888436>
> :
>
> > +.advantages-title {
> +  font-weight: 600;
> +  font-size: 18px;
> +  line-height: 1.22;
> +
> +  color: var(--white);
> +}
> +.advantages-text {
> +  line-height: 1.21;
> +  letter-spacing: -0.02em;
> +  max-width: 308px;
> +
> +  color: rgba(255, 255, 255, 0.7);
> +}
> +
> +.advantages-link {
>
> зараз все добре, тільки маленьке зауваження - іконки не є , a
> , це по аналогії з нашою домашньою. крім того, говер-фокус на них - звідки
> він? на макеті не можу такого знайти
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Melaverde1987/eat-your-chocolate-frog/pull/3#pullrequestreview-1460312336>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6OPUIKYKULA6ED4KIEZUJLXJO2SBANCNFSM6AAAAAAYYUYRFI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2023-06-05 16:57 UTC, Melaverde1987 approved these changes

2023-06-05 16:57 UTC, merged