Subscribe
Melaverde1987/eat-your-chocolate-frog pull request #4
Opened 2023-06-03 07:56 UTC by Andrii111111111

Привет, хтмл,стили и адаптивка есть. Вопрос только в том что вешать на кнопку для модалки?.

2023-06-03 09:20 UTC, Melaverde1987 requested changes

2023-06-03 09:20 UTC, Melaverde1987 commented on src/css/subscribe.css
> +.sub-wrapper {
верхній і нижній паддінги краще поставити на section subscribe, бокові забрати геть, а замість них max-width i margin: 0 auto. але так як є, теж може бути

2023-06-03 09:20 UTC, Melaverde1987 commented on src/partials/subscribe.html
> +      <h1 class="sub-headings">EXPLORE OUR NEW CHOCOLATE FIRST</h1>
це не h1, a h2. де у нас на сторінці буде h1 треба подумати

2023-06-03 09:20 UTC, Melaverde1987 commented on src/css/subscribe.css
> +  width: 128px;
тут задаємо min-width

2023-06-03 09:32 UTC, Andrii111111111 commented on src/css/subscribe.css
> +.sub-wrapper {
Тогда и враппер не нужен по сути?

2023-06-03 09:33 UTC, Andrii111111111 commented on src/partials/subscribe.html
> +      <h1 class="sub-headings">EXPLORE OUR NEW CHOCOLATE FIRST</h1>
ок

2023-06-03 09:33 UTC, Andrii111111111 commented on src/css/subscribe.css
> +  width: 128px;
ок

2023-06-03 10:42 UTC, Andrii111111111 commented on src/css/subscribe.css
> +.sub-wrapper {
ok

2023-06-03 10:47 UTC, Andrii111111111 commented
Все исправил и запушил. Жду проверки.

Сб, 3 июня 2023 г. в 11:20, Melaverde1987 ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/css/subscribe.css
> <https://github.com/Melaverde1987/eat-your-chocolate-frog/pull/4#discussion_r1215365332>
> :
>
> > +
> +.btn-sub:focus,
> +.btn-sub:hover {
> +  background: var(--light-orange);
> +}
> +
> +
> ***@***.*** screen and (min-width: 768px) {
> +  .btn-sub {
> +    width: 172px;
> +    height: 50px;
> +  }
> +
> +}
> +
> +.sub-wrapper {
>
> верхній і нижній паддінги краще поставити на section subscribe, бокові
> забрати геть, а замість них max-width i margin: 0 auto. але так як є, теж
> може бути
> ------------------------------
>
> In src/partials/subscribe.html
> <https://github.com/Melaverde1987/eat-your-chocolate-frog/pull/4#discussion_r1215366361>
> :
>
> > @@ -1,3 +1,16 @@
>  <section class="subscribe">
> -  <div class="container">Subscribe</div>
> +  <div class="container">
> +    <div class="sub-wrapper">
> +      <h1 class="sub-headings">EXPLORE OUR NEW CHOCOLATE FIRST</h1>
>
> це не h1, a h2. де у нас на сторінці буде h1 треба подумати
> ------------------------------
>
> In src/css/subscribe.css
> <https://github.com/Melaverde1987/eat-your-chocolate-frog/pull/4#discussion_r1215366757>
> :
>
> > +
> +
> +.sub-text {
> +  font-size: 14px;
> +  line-height: 1.29;
> +  text-align: center;
> +  letter-spacing: -0.02em;
> +  color: var(--white);
> +  margin-bottom: 24px;
> +  margin-top: 24px;
> +}
> +
> +
> +.btn-sub {
> +  display: block;
> +  width: 128px;
>
> тут задаємо min-width
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Melaverde1987/eat-your-chocolate-frog/pull/4#pullrequestreview-1459119263>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A62G7JOCBCTR6ZFUHFCLZGLXJL6WVANCNFSM6AAAAAAYZELZHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2023-06-03 22:30 UTC, Melaverde1987 commented on src/css/subscribe.css
> +  margin-bottom: 24px;
mb i mt треба забрати, бо йде перебивання стилів, все решта ок, можна буде мержити

2023-06-04 06:39 UTC, Andrii111111111 commented on src/css/subscribe.css
> +  margin-bottom: 24px;
fix

2023-06-05 18:47 UTC, Melaverde1987 approved these changes

2023-06-05 18:47 UTC, merged