How its made
Melaverde1987/eat-your-chocolate-frog pull request #6
Opened 2023-06-03 17:31 UTC by kirostina

2023-06-04 00:07 UTC, Melaverde1987 requested changes

2023-06-04 00:07 UTC, Melaverde1987 commented on src/css/how-its-made.css
> +.how-its-made-section {
потрібний верхній паддінг, а також фоновий колір має не вся секція, а тільки її нижня частина

2023-06-04 00:07 UTC, Melaverde1987 commented on src/css/how-its-made.css
> +  gap: 24px;
gap 18px

2023-06-04 00:07 UTC, Melaverde1987 commented on src/css/how-its-made.css
> +  .how-its-h {
font size тут перебиває попередній

2023-06-04 00:07 UTC, Melaverde1987 commented on src/css/how-its-made.css
> +  .made-video {
блок не центрується, потрібно бокові марджіни авто

2023-06-04 00:07 UTC, Melaverde1987 commented on src/css/how-its-made.css
> +  .made-text {
блок не центрується, потрібно бокові марджіни авто

2023-06-04 00:07 UTC, Melaverde1987 commented on src/css/how-its-made.css
> +.made-list-item {
треба line-height і letter-spacing

2023-06-04 00:07 UTC, Melaverde1987 commented on src/css/how-its-made.css
> +    padding-left: 15px;
на десктопі тут більші паддінги

2023-06-04 00:07 UTC, Melaverde1987 commented on src/css/how-its-made.css
> +  .made-video {
тут інша ширина і замість height краще робити max height

2023-06-04 00:07 UTC, Melaverde1987 commented on src/css/how-its-made.css
> +.container {
стилі контейнера можна взагалі не міняти, а просто писати його в html,бо це загальний клас і він одинаковий для багатьох секції

2023-06-04 22:07 UTC, Melaverde1987 requested changes

2023-06-04 22:07 UTC, Melaverde1987 commented on src/css/how-its-made.css
> +body {
цей клас тут не потрібен, він є у загальних стилях. до речі, цю гілку і мейн треба оновити

2023-06-04 22:07 UTC, Melaverde1987 commented on src/css/how-its-made.css
> +  padding-top: 128px;
паддінг для мобільних тут менший

2023-06-04 22:07 UTC, Melaverde1987 commented on src/partials/how-its-made.html
> +    <a href="howitsmade"></a>
лінк тут зайвий

2023-06-04 22:07 UTC, Melaverde1987 commented on src/css/how-its-made.css
> +.made-video {
висота відео не така, як на макеті, тут можна зробити height або min height

2023-06-04 22:07 UTC, Melaverde1987 commented on src/css/how-its-made.css
> +@media screen and (min-width: 375px) {
container вже є у головних стилях, прописаний для різних ширин

2023-06-06 11:52 UTC, kirostina commented on src/css/how-its-made.css
> +@media screen and (min-width: 375px) {
прибрала

2023-06-06 11:52 UTC, kirostina commented on src/css/how-its-made.css
> +.made-video {
виправила

2023-06-06 11:52 UTC, kirostina commented on src/partials/how-its-made.html
> +    <a href="howitsmade"></a>
прибрала

2023-06-06 11:52 UTC, kirostina commented on src/css/how-its-made.css
> +  padding-top: 128px;
зменшила

2023-06-06 11:53 UTC, kirostina commented on src/css/how-its-made.css
> +body {
прибрала

2023-06-06 11:53 UTC, kirostina commented on src/css/how-its-made.css
> +.container {
прибрала

2023-06-06 11:53 UTC, kirostina commented on src/css/how-its-made.css
> +  .made-video {
виправила

2023-06-06 11:53 UTC, kirostina commented on src/css/how-its-made.css
> +    padding-left: 15px;
виправила

2023-06-06 11:54 UTC, kirostina commented on src/css/how-its-made.css
> +.made-list-item {
додала

2023-06-06 11:54 UTC, kirostina commented on src/css/how-its-made.css
> +  .made-text {
додала

2023-06-06 11:54 UTC, kirostina commented on src/css/how-its-made.css
> +  .made-video {
додала

2023-06-06 11:54 UTC, kirostina commented on src/css/how-its-made.css
> +  .how-its-h {
виправила

2023-06-06 11:54 UTC, kirostina commented on src/css/how-its-made.css
> +.how-its-made-section {
виправила

2023-06-06 14:20 UTC, A-ZuMa approved these changes

2023-06-06 14:20 UTC, A-ZuMa commented on src/partials/how-its-made.html
> +<section id="how-its-made" class="how-its-made-section">
Правільний якір для посилання на секцію "howitsmade"

2023-06-06 15:04 UTC, kirostina commented on src/partials/how-its-made.html
> +<section id="how-its-made" class="how-its-made-section">
виправила

2023-06-06 19:59 UTC, Melaverde1987 approved these changes

2023-06-06 20:00 UTC, Melaverde1987 approved these changes

2023-06-06 20:01 UTC, Melaverde1987 approved these changes

2023-06-06 20:02 UTC, merged