Modal review2
Melaverde1987/eat-your-chocolate-frog pull request #8
Opened 2023-06-04 16:40 UTC by Andrii-13

2023-06-04 17:20 UTC, Melaverde1987 requested changes

2023-06-04 17:20 UTC, Melaverde1987 commented on src/css/modal-review.css
> +  width: 311px;
тут краще зробити так
width: 90%;
    max-width: 311px;
ну і відповідно змінювати для таблета і десктопа, там уже width 100%

2023-06-04 17:20 UTC, Melaverde1987 commented on src/partials/modal-review.html
> +        <form class="modal-review-form">
тут потрібно додати <form action="#"....  бо валідатор буде сварити

2023-06-04 17:20 UTC, Melaverde1987 commented on src/css/modal-review.css
> +  border-radius: 13px;
у мобільній версії border-radius: 8px;
також є filter: drop-shadow(0px 5.44492px 5.44492px rgba(0, 0, 0, 0.03));
він якийсь невидимий, але хай буде

2023-06-04 17:20 UTC, Melaverde1987 commented on src/css/modal-review.css
> +  margin-left: 20px;
правий марджін у мобільному трохи менший

2023-06-04 17:20 UTC, Melaverde1987 commented on src/css/modal-review.css
> +.modal-review-btn {
відстань між textarea і кнопкою знизу трохи більша

2023-06-04 17:20 UTC, Melaverde1987 commented on src/css/modal-review.css
> +  max-width: 100%;
краще писати max-width 255px, ширину взагалі тоді не треба

2023-06-06 12:54 UTC, Andrii-13 commented on src/css/modal-review.css
> +  width: 311px;
виправлено

2023-06-06 12:59 UTC, Andrii-13 commented on src/css/modal-review.css
> +  border-radius: 13px;
виправив

2023-06-06 13:06 UTC, Andrii-13 commented on src/css/modal-review.css
> +  margin-left: 20px;
виправлено

2023-06-06 13:12 UTC, Andrii-13 commented on src/css/modal-review.css
> +.modal-review-btn {
не зрозумів. там я поставив gap=18px як по макету. в усіх 3 варіантах вона однакова.!!

2023-06-06 13:13 UTC, Andrii-13 commented on src/css/modal-review.css
> +  max-width: 100%;
зроблено

2023-06-06 13:28 UTC, Andrii-13 commented on src/partials/modal-review.html
> +        <form class="modal-review-form">
виправлено

2023-06-06 18:44 UTC, Melaverde1987 approved these changes

2023-06-06 18:44 UTC, merged