Modal explore
Melaverde1987/eat-your-chocolate-frog pull request #9
Opened 2023-06-04 16:54 UTC by Andrii-13

2023-06-04 21:42 UTC, Melaverde1987 requested changes

2023-06-04 21:42 UTC, Melaverde1987 commented on src/css/modal-explore.css
> +.modal-explore {
також краще так
max-width: 311px;
    width: 90%;

2023-06-04 21:42 UTC, Melaverde1987 commented on src/partials/modal-explore.html
> +        <form class="modal-explore-form">
потрібен form action="#"

2023-06-04 21:42 UTC, Melaverde1987 commented on src/partials/modal-explore.html
> +            <input type="email" class="explore_user_email" placeholder="Enter your email" required>
input повинен мати name, а також id, бо тут лейбл його не огортає

2023-06-04 21:42 UTC, Melaverde1987 commented on src/partials/modal-explore.html
> +                <use href="../img/sprite.svg#close">
достатньо одної крапки

2023-06-04 21:42 UTC, Melaverde1987 commented on src/partials/modal-explore.html
> +            <input type="email" class="explore_user_email" placeholder="Enter your email" required>
назви класів не мають мати нижнього підкреслення

2023-06-06 12:14 UTC, Andrii-13 commented on src/partials/modal-explore.html
> +            <input type="email" class="explore_user_email" placeholder="Enter your email" required>
виправлено

2023-06-06 12:15 UTC, Andrii-13 commented on src/partials/modal-explore.html
> +                <use href="../img/sprite.svg#close">
виплавлено

2023-06-06 12:15 UTC, Andrii-13 commented on src/partials/modal-explore.html
> +            <input type="email" class="explore_user_email" placeholder="Enter your email" required>
додав name="user_email"

2023-06-06 12:28 UTC, Andrii-13 commented on src/partials/modal-explore.html
> +        <form class="modal-explore-form">
добавив. також добавив name

2023-06-06 12:39 UTC, Andrii-13 commented on src/css/modal-explore.css
> +.modal-explore {
виправив.  max-width:90%, width:311px;

2023-06-06 13:45 UTC, Andrii-13 commented on src/css/modal-explore.css
> +.modal-explore {
виправив max-width: 311px;
width: 90%;

2023-06-06 18:37 UTC, Melaverde1987 approved these changes

2023-06-06 18:38 UTC, merged